### ISSUE TITLE
Update Docker image on kubernetes deployment files

### ISSUE THREAD

**Issue by AndreaGiardini** [dependabot/feedback#264]
It would be nice to have the possibility to have the docker image update logic also for Kubernetes deployment files.

Dependabot will have to scan all yml/yaml files, get the `image` field and check for updates of the docker image.

**Comment by greysteil** [comment]
Agreed! @hmarr - any thoughts on what this would look like as a "package manager"?

**Comment by RohanNagar** [comment]
Along these lines, support for `docker-compose` would be awesome as well! This is also described in #82

The images are defined in the same way as in the Kubernetes files: `docker-compose` is a `yaml` file and the images are defined in `image` fields.

**Comment by greysteil** [comment]
Totally is - I can think of two ways:
1) all of the work on this one will be in [dependabot-core](https://github.com/dependabot/dependabot-core). Happy to talk you through what needs doing there - maybe take a look at the readmes (particularly [this section](https://github.com/dependabot/dependabot-core#architecture)) first? Actually adding the code yourself would be quite a big undertaking - it's quite a big codebase these days!
2) a smaller, more accessible way to help would be to put together a bunch of fixtures, commented up with the kind of updates you'd want from Dependabot on them. A PR into Dependabot Core that just added those (under the `spec/fixtures` directory) which a bunch of comments on GitHub would make it way easier for me to pick this up.

Thanks for your enthusiasm on this one, and sorry for letting it stall. Lots on at the mo!

**Comment by genebean** [comment]
+1 to this functionality

**Comment by ajcann** [comment]
Would be great to see this - checking yaml in specified folders for the key containers: [ image: <dockerimage> ] for kubernetes and probably explicit specification of a docker-compose file looking for: services: { <service>: image: <dockerimage> }

**Comment by steinbrueckri** [comment]
+1 to this functionality

**Comment by gavinelder** [comment]
+1  to this functionality

**Comment by devstein** [comment]
+1

**Comment by RappC** [comment]
+1

**Comment by ChipWolf** [comment]
+1

**Comment by ChipWolf** [comment]
+1
I also think it would be a good addition to allow some arbitrary regex to select the location of the dependancy in code and the ability to specify a source of the current version.

Take this HelmRelease definition as an example:
`workloads/rabbitmq/helm-release.yaml`
```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
...
spec:
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: rabbitmq
    version: 3.3.6
```

 The following regex will match any valid major.minor.patch version in this file:
```regexp
^    version: (0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)?$
```

My dependabot config would then become something along the lines of:
```yaml
version: 1
update_configs:
  - package_manager: "git_tags"
    directory: "/"
    update_schedule: "weekly"
    configs:
      - source: "https://raw.githubusercontent.com/bitnami/charts/master/bitnami/rabbitmq/Chart.yaml"
        source_match: "^version: (0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)?$"
        destination: "workloads/rabbitmq/helm-release.yaml"
        destination_match: "^    version: (0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)?$"
```

Any thoughts?
