### ISSUE TITLE
Python override index

### ISSUE THREAD

**Issue by sigmyers** [dependabot/feedback#325]
Hi there,

I have an index-url and extra-index-url supplied in my requirements.txt files.

The index-url is behind our VPN and we want to monitor/bump that dependency manually -- we have no way to expose our internal artifactory instance even with an auth token on our end (security, etc.).

My question is this -- I've added a config variable to override and only look at the default pypi package manager as opposed to our index-url, with the hope it will just fail for that one dependency and we can ignore it, however I'm not seeing any version bumps after adding that config variable pointing to: https://pypi.python.org/pypi/ -- even after forcibly downgrading a particular dependency (boto) and expecting to see a version bump PR filed.

Any ideas?  Any additional insight I can provide to see if there's a workaround?  

I've also added  a yaml file:

```
version: 1
update_configs:
  # Keep package.json (& lockfiles) up to date as soon as
  # new versions are published to the npm registry
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
  # Keep python up to date, batching pull requests weekly
  - package_manager: "python"
    directory: "/"
    update_schedule: "weekly"
    ignored_updates:
    - match:
      dependency_name: "internal-special-lib"
      # The range format is specific to the package manager
      version_requirement: "1.x"
```
