### ISSUE TITLE
update_type improvements

### ISSUE THREAD

**Issue by cihati** [dependabot/feedback#340]
Per https://github.com/dependabot/dependabot-core/issues/956 , I learned that `update_type` can have only `security` and `all` values in `allowed_updates`. But for `automerged_updates`, it can have other values such as `security:patch`, `semver:minor`, `semver:patch`. I think `update_type` should behave predictably to allow for more intuitive use and extra features (e.g. only allowing non-major version jumps in dependabot PRs)

**Comment by greysteil** [comment]
Thanks for porting this across @cihati!

**Comment by chenrui333** [comment]
Just want to circle back on this to check if we can have multiple `update_type` values applied for one `dependency_name` now?

**Comment by cetinajero** [comment]
It would be awesome to have those `update_type` options available on the `allowed_updates` and `ignored_updates` keys.

I'm trying to ignore the patch updates (only the ones that aren't a security update) for an specific dependency and it didn't worked out:

**config.yml**

```yaml
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    ignored_updates:
      - match:
          dependency_name: "firebase"
          update_type: "semver:patch"
```

**Error:**

```
The property '#/update_configs/0/ignored_updates/0/match' contains additional properties ["update_type"] outside of the schema when none are allowed
```

i.e. `ignored_updates` don't support `update_type` option.
