### ISSUE TITLE
Simple list for ignored_updates entry in config file

### ISSUE THREAD

**Issue by samselikoff** [dependabot/feedback#373]
Just dipping my toes into dependabot, great work on this awesome project!

I'm wondering if there's a simpler way to list out deps in `ignored_updates`. Right now my config file looks like this:

```yaml
version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    ignored_updates:
      - match:
          dependency_name: "broccoli-asset-rev"
      - match:
          dependency_name: "ember-ajax"
      - match:
          dependency_name: "ember-cli"
      - match:
          dependency_name: "ember-cli-dependency-checker"
      - match:
          dependency_name: "ember-cli-eslint"
      - match:
          dependency_name: "ember-cli-htmlbars"
      - match:
          dependency_name: "ember-cli-htmlbars-inline-precompile"
      - match:
          dependency_name: "ember-cli-inject-live-reload"
      - match:
          dependency_name: "ember-cli-qunit"
      - match:
          dependency_name: "ember-cli-shims"
      - match:
          dependency_name: "ember-cli-sri"
      - match:
          dependency_name: "ember-cli-uglify"
      - match:
          dependency_name: "ember-disable-prototype-extensions"
      - match:
          dependency_name: "ember-export-application-global"
      - match:
          dependency_name: "ember-load-initializers"
      - match:
          dependency_name: "ember-maybe-import-regenerator"
      - match:
          dependency_name: "ember-resolver"
      - match:
          dependency_name: "ember-source"
      - match:
          dependency_name: "ember-source-channel-url"
      - match:
          dependency_name: "ember-try"
      - match:
          dependency_name: "eslint-plugin-ember"
      - match:
          dependency_name: "eslint-plugin-node"
      - match:
          dependency_name: "loader.js"
      - match:
          dependency_name: "qunit-dom"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "in_range"
```

Perhaps `ignored_updates` could take a simple list of package names? Something like

```yaml
version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    ignored_updates:
      - "broccoli-asset-rev"
      - "ember-ajax"
      - "ember-cli"
      - "ember-cli-dependency-checker"
      - "ember-cli-eslint"
      - "ember-cli-htmlbars"
      - "ember-cli-htmlbars-inline-precompile"
      - "ember-cli-inject-live-reload"
      - "ember-cli-qunit"
      - "ember-cli-shims"
      - "ember-cli-sri"
      - "ember-cli-uglify"
      - "ember-disable-prototype-extensions"
      - "ember-export-application-global"
      - "ember-load-initializers"
      - "ember-maybe-import-regenerator"
      - "ember-resolver"
      - "ember-source"
      - "ember-source-channel-url"
      - "ember-try"
      - "eslint-plugin-ember"
      - "eslint-plugin-node"
      - "loader.js"
      - "qunit-dom"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "in_range"
```
