### ISSUE TITLE
How to configure dependabot to only update packages within a certain range?

### ISSUE THREAD

**Issue by connorshea** [dependabot/feedback#395]
So [in my project I have a config.yml](https://github.com/connorshea/ContinueFromCheckpoint/blob/26946e8021d4937e718ea42ad98ccfb458350c55/.dependabot/config.yml) for my yarn packages that looks like this:

```yaml
 - package_manager: "javascript"
    directory: "/"
    # Allow all direct dependencies to be updated, only allow indirect
    # dependencies to update when there's a security release.
    allowed_updates:
      - match:
          update_type: all
          dependency_type: direct
      - match:
          update_type: security
          dependency_type: indirect
    # Disallow updates past 4.x for webpack and 3.x for webpack-dev-server.
    # Webpacker 4.x only supports webpack 4.x.
    ignored_updates:
      - match:
          dependency_name: "webpack"
          version_requirement: "4.x"
      - match:
          dependency_name: "webpack-dev-server"
          version_requirement: "3.x"
```

My goal here is this:

- `webpack-dev-server` can be upgraded from its current version (3.1.14) to any version within the 3.x  series (3.2.0, 3.3.0, 3.3.1, etc.)
- `webpack-dev-server` cannot be upgraded to `4.0.0` or any version past that.
- `webpack` can be upgraded to any version within the 4.x series but not to 5.0.0 or anything past 5.0.0.

But it doesn't seem like dependabot is ever upgrading `webpack-dev-server` despite there being newer versions of `webpack-dev-server` available within the 3.x range. It's a devDependency, if that matters. Does that count as an indirect dependency, or am I using the `version_requirement` attribute incorrectly?

Thanks as always :)
