### ISSUE TITLE
[python] having pyproject.toml‎ breaks the bot

### ISSUE THREAD

**Issue by amureki** [dependabot/feedback#407]
Hi dependabot fellows,

we did add `pyproject.toml‎` to configure Black formatter in one of our repositories.
File looks like this:

```toml
[tool.black]
skip_string_normalization = true
```

And is not related to our dependencies management at all (we are not using poetry there).

I believe, this should be handled and such files without defined requirements should be skipped there.

Could you, please, take a look?

Thank you,
Best,
Rustem
