### ISSUE TITLE
Support Rust Conditional Dependencies

### ISSUE THREAD

**Issue by sunjay** [dependabot/feedback#448]
1. I had this issue open for a while to update `piston_window`: https://github.com/sunjay/turtle/pull/119
2. I then updated my `Cargo.toml` file here: 
https://github.com/sunjay/turtle/blob/64380076c9dba368e622edb10298c48022619d42/Cargo.toml
3. The dependencies section now looks like:
```toml
[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"

interpolation = "0.1"
rand = "0.5"

# Dependencies that don't support / shouldn't be used with WASM
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
piston_window = "0.73"
```
4. I got a message from dependabot saying:
> Looks like piston_window is no longer a dependency, so this is no longer needed.

I think it's because the dependency is now conditional with `cfg(not(target_arch = "wasm32"))`. 

It would be really great if dependabot could support this way of configuring dependencies.

The approach I've taken here to conditionally use a dependency is very common, especially for WebAssembly work which is getting more and more popular in the community. 

Thanks for making a great product!
