### ISSUE TITLE
Ignore this dependency not working

### ISSUE THREAD

**Issue by vaibhavhrt** [dependabot/feedback#462]
On the PR of python dependency `botocore` I have commented 3-4 times `@dependabot ignore this dependency` but everyday I keep getting a new PR from the bot. The package `boto3` depends on `botocore` so when `boto3` updates `botocore` updates as well, so I don't need a seperate PR for `botocore`.

I can't link the PR's as it's a private repo. But I have commented on that PR mentioning depandabot and linking this issue.

Here is a screenshot:
![image](https://user-images.githubusercontent.com/22582828/57431474-8f619d00-7250-11e9-8e01-79fc2a2dfcc5.png)

**Comment by vaibhavhrt** [comment]
I have told depandabot to ignore botocore in four different PR's. I have mentioned depandabot and linked this issue in all those PR, you should be able to investigate.

**Comment by feelepxyz** [comment]
@vaibhavhrt sorry about this, having a look!

**Comment by feelepxyz** [comment]
Hey this is currently by design 🙁 It's happening because you've opted in to receive all updates (including sub-dependencies) and `botocore` is a sub-dependency of `boto3`.

Whenever you comment to ignore a dependency it will be ignored until it has been updated, it's being updated in the `boto3` update and because of this the ignore setting is deleted causing the separate `botocore` update again.

To fix this issue you could either disable sub-dependency updates by checking the filter option in your [dashboard](https://app.dependabot.com/accounts/vaibhavhrt/projects/34923): "Only top-level dependencies (and security patches for subdependencies)" or switch over to config files where your ignored updates are persisted. Check out the docs here: https://dependabot.com/docs/config-file/

**Comment by vaibhavhrt** [comment]
@feelepxyz thanks, I will create a config file.
- Is there some way to generate an initial config.yaml from the settings I already have on depandabot dashboard.
- If I create a config file in one of my repo but don't add that repo in depandabot dashboard, will depandabot start checking that repo too. (Maybe add it to my depandabot dashboard automatically).
- What if there is a conflict between my settings on depandabot dashboard and config file. For example Config file says update everyday but but on the depandabot dashboard I set it to be weekly. Which one will take precedence.

**Comment by feelepxyz** [comment]
@vaibhavhrt cool, here's your current setup as a config file:

```yml
---
version: 1
update_configs:
  - package_manager: python
    update_schedule: daily
    directory: "/"
    allowed_updates:
      - match:
          update_type: all
          dependency_type: direct
      - match:
          update_type: all
          dependency_type: indirect
  - package_manager: javascript
    update_schedule: daily
    directory: "/frontend"
```

As long as Dependabot is authorised to access the repo you should only need to add the config file in each repo in `.dependabot/config.yml` for it to be automatically added to the dashboard. The config file always takes precedent so any old dashboard config will be deleted. You'll also not be able to edit the config from the dashboard anymore and need to explicitly make changes to the config file.
