### ISSUE TITLE
No idea how to fix "Automerging is not enabled for this account" 

### ISSUE THREAD

**Issue by lucasmazza** [dependabot/feedback#476]
While setting up the `.dependabot/config.yml` for one of our repos, I attempted to enable the `automerged_updates` but we receive the automatic issue mentioning that `Automerging is not enabled for this account`, while the config validator from https://dependabot.com/docs/config-file/validator/ says everything is fine. Our config looks something like this:

```yaml
version: 1

update_configs:
  - package_manager: "elixir:hex"
    directory: "/"
    update_schedule: "daily"

    default_reviewers:
      - "..."
      - "..."
    default_assignees:
      - "..."
      - "..."
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "semver:minor"
```

Googling around for this message yielded 0 results, and the docs on the config file doesn't mentions any prerequisites/restrictions on enabling auto updates 🤔

**Comment by alanvardy** [comment]
Encountering same issue (this is a non-critical account with good code coverage)

```yml
version: 1
update_configs:
  # required properties omitted ...
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "live"
    default_reviewers:
    - "alanvardy"
    automerged_updates:
      - match:
        dependency_type: "all"
        update_type: "all"
```
