### ISSUE TITLE
no longer updatable

### ISSUE THREAD

**Issue by lusoalex** [dependabot/feedback#483]
Dear,
I am playing with .dependabot/config.yml to give some sample to my organization.  

I first setup a java:maven project as below which successfuly end up to a PR.

```
version: 1
update_configs:
  - package_manager: "java:maven"
    directory: "/mavenjava"
    update_schedule: "daily"
    default_reviewers:
      - "lusoalex"
    default_assignees:
      - "lusoalex"
```

Then I have added a npm folder as below:

```
version: 1
update_configs:
  - package_manager: "java:maven"
    directory: "/mavenjava"
    update_schedule: "daily"
    default_reviewers:
      - "lusoalex"
    default_assignees:
      - "lusoalex"

  - package_manager: "javascript"
    directory: "/npmjs"
    update_schedule: "live"
```

Which result in creating a new PR for my npmjs folder but also closed the previous PR (for java) with as comment: 

> Looks like io.vertx:vertx-core is no longer updatable, so this is no longer needed.

Do you know if there is any bug related to a multiple folder/settings within a single repository?

Regards,
Alexandre.
