### ISSUE TITLE
Feature request: Auto-merging of devDependencies for javascript

### ISSUE THREAD

**Issue by jwalton** [dependabot/feedback#521]
Most of my javascript packages are heavy on dev dependencies (babel and it's assorted plugins, lint-staged for linting on commit, husky for running lint-staged, the typescript compiler, etc...) and every time one of these gets updated, I get a huge list of PRs from dependabot.

But for dev dependencies especially, if the tests pass, it's probably good to merge without any further interaction from me.  It would be nice if there was an option somewhere that said, "Ok dependabot, for this project, if you update a dev dependency, and the tests pass, just go ahead and merge it".  Maybe skip the PR step entirely.

**Comment by feelepxyz** [comment]
@jwalton this is possible!

From the dashboard you can do it if you click on the cog for the repo you want:
<img width="1332" alt="Screenshot 2019-06-12 at 18 22 05" src="https://user-images.githubusercontent.com/20165/59372448-6f396800-8d3f-11e9-9f1d-38ebe068e9f3.png">

Or using config files: https://dependabot.com/docs/config-file/#automerged_updates 

```yaml
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
```
