### ISSUE TITLE
repositories stopped getting updates

### ISSUE THREAD

**Issue by MadMango** [dependabot/feedback#620]
Hello!

I've recently turned dependabot on for a few private repos, there have been quite a few outdated dependencies but those are sorted now and there aren't any more outstanding PRs from dependabot.

I'm sure that there are still new versions of the packages in those repositories though, but even if I trigger an update manually, no new PRs are generated.

This is the config for one of the repos:

```
---
update_configs:
- directory: "/"
  package_manager: javascript
  update_schedule: daily

In addition, the following defaults have been applied:

---
allowed_updates:
- match:
    update_type: all
    dependency_type: direct
- match:
    update_type: security
    dependency_type: indirect
automerged_updates: []
default_assignees: []
default_labels:
- dependencies
default_reviewers: []
ignored_updates: []
target_branch: develop
version_requirement_updates: auto
```

Everything seems fine to me here, it's mostly using defaults, is there anything else I can do to check what might be causing it?

Thanks!
Mat
