### ISSUE TITLE
Dependabot doesn't see .csproj files

### ISSUE THREAD

**Issue by richlander** [dependabot/feedback#632]
I tried to add [richlander/samples](https://github.com/richlander/samples) to dependabot. 

I see:
![image](https://user-images.githubusercontent.com/2608468/63060085-118fdc00-bea6-11e9-8139-78bae49cdb56.png)

There are lots:

![image](https://user-images.githubusercontent.com/2608468/63060185-5ca9ef00-bea6-11e9-8a20-6931a480c7bf.png)

Many of them don't have `PackageReference` entries, but some of them do. Here is a good example: https://github.com/richlander/samples/blob/master/machine-learning/tutorials/TaxiFarePrediction/TaxiFarePrediction.csproj

Am I doing something wrong?

Related (but I think different) issue: https://github.com/dependabot/feedback/issues/557

**Comment by greysteil** [comment]
Looks like all of those files are nested - you can specify a directory when adding Dependabot to a repo. Alternatively, if you have a `.sln` file that points to those projects you can point Dependabot at the repo with that `.sln` file in it.

**Comment by greysteil** [comment]
(Any feedback on how we could do better on this one very welcome, btw! We don't clone your repo so it's tricky for us to walk the whole repository tree...)

**Comment by richlander** [comment]
OK. That's a tall order for large repos, although we could build a tool for that.

I saw this example: https://github.com/dependabot/dependabot-core/blob/master/.dependabot/config.yml

What pattern would you expect to see for a repo that is all one language?

```yml
update_configs:
  - package_manager: "dotnet:nuget"
    directory: "/one"
    directory: "/two"
    directory: "/three"
    update_schedule: "daily"
```

or

```yml
update_configs:
  - package_manager: "dotnet:nuget"
    directory: "/one"
    update_schedule: "daily"
  - package_manager: "dotnet:nuget"
    directory: "/two"
    update_schedule: "daily"
  - package_manager: "dotnet:nuget"
    directory: "/three"
    update_schedule: "daily"
```
