### ISSUE TITLE
Add option to update only development dependencies

### ISSUE THREAD

**Issue by d7my11** [dependabot/feedback#643]
Hi.

We use `dependabot` to manage our dependency updates, and we would like to have an option to update only development dependencies along with `Only security updates`.

in `javascript` package manager would be updating `devDependencies`
in `ruby:bundler`  would be `:development` group

could be added as a type, and used in the config file as well:

```yml
- match:
  update_type: "dev"
```

What do you think and we can open a PR if the idea is approved, thanks.

**Comment by feelepxyz** [comment]
You can specify this in the config file using `allowed_updates`: https://dependabot.com/docs/config-file/#allowed_updates

I'll add it to the docs too but you can add it like this:

```yaml
version: 1
update_configs:
  # required properties omitted ...
  allowed_updates:
    - match:
        dependency_type: "development"
```
