### ISSUE TITLE
Not bumping major versions

### ISSUE THREAD

**Issue by caseyWebb** [dependabot/feedback#652]
I have [a repo](https://github.com/Profiscience/eslint-config-profiscience) with the following .dependabot.yml

```yml
version: 1
update_configs:
  - package_manager: javascript
    directory: /
    update_schedule: live
    automerged_updates:
      - match:
          dependency_type: all
          update_type: semver:minor
    version_requirement_updates: increase_versions
```

and I am not receiving dependabot PRs for major version updates to @typescript-eslint/eslint-plugin or @typescript-eslint/parser. I tried adding the following block and triggering an update to no avail.

```yml
    allowed_updates:
      - match:
          update_type: "all"
```
