### ISSUE TITLE
False "Missing file" error

### ISSUE THREAD

**Issue by tdukart** [dependabot/feedback#686]
Dependabot opened an issue in one of my private repositories about a missing `package-lock.json` file, although the file existed. I believe it was opened during this morning's GitHub incident (https://www.githubstatus.com/incidents/b54zv9nz8m01), so it could have simply been that the file looked to be missing during the API issues and the bot didn't handle the outage as gracefully as it could have.

The repository in question has the following `.dependabot/config.yml` file:
```yml
version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "security"
      - match:
          dependency_name: [redacted]
```

I did mention `@dependabot` in a comment on the issue, but since it's a private repo I'm not sure how much visibility the maintainers have into it.
