### ISSUE TITLE
automerged_updates doc example is incorrect

### ISSUE THREAD

**Issue by nikolas** [dependabot/feedback#691]
When I put example 1 from here into the [dependabot config validator](https://dependabot.com/docs/config-file/validator/), I get the error:
> The property '#/update_configs' of type object did not match the following type: array

https://dependabot.com/docs/config-file/#automerged_updates

What is the correct syntax for automerged_updates? This example is apparently incorrect:

```
version: 1
update_configs:
  # required properties omitted ...
  automerged_updates:
    - match:
        dependency_type: "development"
        # Supported dependency types:
        # - "development"
        # - "production"
        # - "all"
        update_type: "all"
        # Supported updates to automerge:
        # - "security:patch"
        #   SemVer patch update that fixes a known security vulnerability
        # - "semver:patch"
        #   SemVer patch update, e.g. > 1.x && 1.0.1 to 1.0.3
        # - "semver:minor"
        #   SemVer minor update, e.g. > 1.x && 2.1.4 to 2.3.1
        # - "in_range"
        #   matching the version requirement in your package manifest
        # - "all"
    - match:
        dependency_type: "production"
        update_type: "semver:patch"
```

**Comment by yaroslavmo** [comment]
I was confused too, at first. There is a `# required properties omitted ...` section. You should add the required parameters for it to pass validation.

**Comment by nikolas** [comment]
Yeah, the correct syntax requires the project directory, and an additional level of indentation, like this:
```
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/eclipsing-binary-simulator/"
    update_schedule: "live"
    version_requirement_updates: "increase_versions_if_necessary"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
```

I can't find where to update the docs, or i'd do it myself.
