### ISSUE TITLE
Use a config file instead of relying entirely on dependabot.com

### ISSUE THREAD

**Issue by nesl247** [dependabot/feedback#70]
I was looking at several issues, and the one thing that kept coming to mind was it would be easier if there was simply a `.dependabot.json` file in each repo. This would allow us to copy the file between repos, and configure dependabot on a fresh repo as well.

I would imagine something like this (based only on the features I've used so far, I know there are more):

```json
{
  "enabled": "true",
  "languages": {
    "php": {
      "bump": "daily",
      "security_only": false,
      "lockfile_only": true,
    },
    "ruby": {
      "bump": "weekly",
    },
    "javascript": {},
  }
}
```

Doing this, I would make it so it does not fail to run any language if it isn't in the repo. This way a single file could be copied over to ever repo, and if the language is detected, it works, if not, the language is skipped for updates.

**Comment by greysteil** [comment]
I've been holding back on this because I want Dependabot's configurability to stabilise in the dashboard before introducing a file format. I definitely agree that a configuration file will be a good idea at some point, though. 🙂

**Comment by nesl247** [comment]
One thing that may make it easier to do it now, rather than waiting (and I say this because of how annoying it is to configure the 200 repos that my company has, and thus I know others experience this), is to add a version to the config file.

```json
{
  "version": 1
}

{
  "version": 1.1
}

{
  "version": 2
}
```

etc. If you look at docker-compose, they do this pretty nicely. This way you can have a different parser per version, and support older versions without requiring a ton of stability. If you are on a v1 config for example, you can't configure anything available in v1.1 or v2, etc., but that isn't a big deal. There dependabot would use whatever defaults it would use today.

**Comment by Jym77** [comment]
Config file as suggested would allow a nice granularity at the package level. 

Typically, I can totally allow the auto-merged deps (whitelisted) to be bumped daily but the other ones are kinda spamming me with PR so weekly or monthly bump is better for my workflow…
And of course, versioning the config API allows to still evolve the code. At the same time, it also kinda force to maintain legacy code for reading the old versions of the config file, so I understand if devs want to stabilise options first…

Config file also has the nice property of putting all the config inside the repo rather than on external stuff. Everything in one place makes it easier to follow what happens.

**Comment by simlu** [comment]
Would be very interested in this as well. I'm currently switching a lot of repos from greenkeeper to dependabot and a config file would make it so much easier!

**Comment by greysteil** [comment]
👍, and sorry it's manual at the moment @simlu!

**Comment by php-coder** [comment]
> if there was simply a .dependabot.json file in each repo

I'd prefer having YAML file (like TravisCI and others).

**Comment by nesl247** [comment]
@php-coder That's good too. I don't really care what the format is, I just want a config file of some sort.

**Comment by davidgoate** [comment]
@greysteil one thing that might help IMO would be to consider the ability via the dashboard to link the org to a single repo containing the config.

it is true that i can copy and pasta a file or use git submodules to do this. But, if i have 30 repos in one org all following similar structures it'b be cool to allow  for having a single config file in version control via a link to the repo where i can update the config file once for everything. 

If the feature gets more mature, perhaps if the config is present in an individual repo it could override the "org master config"...

**Comment by feelepxyz** [comment]
@davidgoate I hear you, definitely want to get to a point where you don’t need to do lots of repeated tasks to use dependabot!

I’d want to start by  building this for individual repos and get that solid before adding shared/global configs but definitely something we need to consider when managing lots of repos. 

Currently the config is applied per repo/project so we need to start by doing it at that level so we can migrate the existing settings to a file. We’d also want to keep this file in sync with the dashboard.

**Comment by simlu** [comment]
@davidgoate While I understand your use case, I don't think it is the responsibility of dependabot to do this. All other tools (circle, travis, greenkeeper, gally, etc) don't allow you to do that and if you have thirty repos in one organization you hopefully enforce structure already by other means. That's where the dependabot config should be managed.

As an example, we use js-gardener (disclaimer I'm the author) to enforce a lot of consistency. However we have another dependency that manages a lot of files and does structure tests. All our repos use that dependency. This means when we need to update a managed file we do it once and it propagates slowly everywhere as we update the dependency.

Tldr; great to do, but shouldn't be done by dependabot. Noone else does it, so you already need to deal with reducing redundancy anyways.

**Comment by simlu** [comment]
@davidgoate Honestly, I'd consider disabling the dashboard if a config is present. Dashboard is the "quick and easy way" to get started, but once you use a config that should be your source of truth. Don't mix, it would just cause a lot of confusion. I also wouldn't mind requiring config and disabling the dashboard options entirely (I'm suprised you didn't go that way initially since Gui maintenance is costly as you know).

**Comment by davidgoate** [comment]
@simlu I do take you point, I think it's fair overall but I'm also keen to learn more about specifically the workflow in the dependabot case for:

> if you have thirty repos in one organization you hopefully enforce structure already by other means

Assuming I have 30 repos a few ways I can think of enforcing structure:

* have all repos referring to a git submodule which holds the config. - would require 30 submodule updates (granted can be automated in a CI or via a bash script etc..., but does require checking out the 30 repos and making the submodule update and pushing the 30 back to source control.
* Perhaps the usecase above can actually have dependabot do it for you, e.g dependabot sees the new submodule and updates it automatically in all repos.
* use the project generator we have which holds a template to create a new repo and "blank project" - but this would only introduce the "new" config for new repos built after a config change.
* Use a custom built bash script or similar to make the change in all projects and commit the change.

I'm sure there are other ways to do this too, perhaps you'll suggest a much better one.

**Comment by davidgoate** [comment]
Two areas where we, as users of dependabot, feel pain using it right now are:

1. Every time we create a new repository, waiting for the first PR of each "type", e.g. Docker, Maven and then on each one add reviewers and assignees (which for us right now are always the same) and then tag dependabot with 

> @dependabot use these reviewers

> @dependabot use these assignees

Then after that do the same for the automerge config per repo & type again, e.g. Maven allow patch level auto merge. Assuming approx 30 repos and using both docker and maven in these we're doing that approximately 60 times at the moment. Whatever solution that comes from this would be beneficial to us if it were somehow usable to reduce this repetition. I take the points above about having various ways to manage config across repos - I've detailed 4 ways that I think this could be achieved, but IMO none of them are as "user friendly" as having dependabot just provide a single org wide setting. I agree it can get complex if the feature were to try to allow things like overriding, but there could be a simple rule like, if a config file exists in the repo then it's entirely repo specific managed - if there isn't an org wide default could apply.

If there is a better way, other than the 4 I detailed in my comments above to manage this I'd love to learn about it, as IMO all 4 that I list above suffer some drawback. I love the work dependabot is doing, I'm kist trying to feed in some input as a fairly heavy user as to what causes me pain and how I'd find this product better to use. 👍  for all the great features so far, I'm sure dependabot has saved us days of time already.

**Comment by feelepxyz** [comment]
@davidgoate great feedback! I'm currently working on a page in the dashboard where you'll be able to view and edit the reviewers, assignees, labels (and ignored deps) which would slightly improve the situation.

I like your idea of allowing either a global config defined in the dashboard or a config file per repo. We have a couple of projects lined up before we get to this so hang in there!

**Comment by cabello** [comment]
This would be very useful for us as well, use case: we have a micro-services infra-structure and we use separate repos, like we generate continuous integration configuration in the service generator script, it would be nice to also be able to configure dependabot out of the box.

**Comment by wvh-shanee** [comment]
Thanks, @greysteil for linking to #234--I searched for 'yml' before creating it and missed this one because it was a .json suggestion.  Looking forward to a config file!

**Comment by feelepxyz** [comment]
> @greysteil one thing that might help IMO would be to consider the ability via the dashboard to link the org to a single repo containing the config.
> 
> it is true that i can copy and paste a file or use git submodules to do this. But, if I have 30 repos in one org all following similar structures it'b be cool to allow for having a single config file in version control via a link to the repo where I can update the config file once for everything.
> 
> If the feature gets more mature, perhaps if the config is present in an individual repo it could override the "org master config"...

**Comment by feelepxyz** [comment]
Oops, not done yet! FYI, we've started working on config files so should have something to try out in the coming weeks.

**Comment by feelepxyz** [comment]
Hey, we now have a first version of config files ready for beta testing 🎉

We would love your feedback on usability before we roll this out to everyone.

We're focused on improving usability before adding any new config features,
so extra keen to hear any issues around ease of use for the current set of options.

To get started, add the following file to the root of your repo: `.dependabot/config.yml`

## Caveats
- **The current config format is subject to breaking changes** for another couple
weeks until we've ironed out any issues or inconsistencies
- You can't specify any ignored updates yet, we're currently working on adding
support for this

## Simple example `.dependabot/config.yml`
#### With only required properties
```yml
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"

  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "live"
```

## Full example `.dependabot/config.yml`
#### With all optional properties
```yml
version: 1
update_configs:
  - package_manager: "ruby:bundler"
    # Supported package managers:
    # - "javascript",
    # - "ruby:bundler",
    # - "php:composer",
    # - "java:maven",
    # - "elixir:hex",
    # - "rust:cargo",
    # - "java:gradle",
    # - "dotnet:nuget",
    # - "go:dep",
    # - "go:modules",
    # - "docker",
    # - "elm",
    # - "submodules",
    # - "python",
    # - "terraform"

    # Relative to repository's root
    directory: "/"

    update_schedule: "live"
    # Available schedules:
    # - "live"
    #     Only supported by the following package managers:
    #     - javascript
    #     - ruby:bundler
    #     - php:composer
    #     - rust:cargo
    #     - elixir:hex
    #     - python
    #
    # - "daily"
    # - "weekly"
    # - "monthly"

    # Branch to create pull requests against
    # If blank, Dependabot will use your repo's default branch
    target_branch: "develop"

    default_reviewers:
      - "github_username1"
      - "github_username2"

    default_assignees:
      - "github_username"

    custom_labels:
      - "existing label to use"

    # Specify which update PRs should be merged automatically
    #
    # For all of the options below Dependabot will wait until all your
    # status checks pass before merging. You can also set working hours
    # for automerging in your Dashboard account settings.
    automerged_updates:
      - match:
          dependency_group: "development"
          # Supported dependency groups:
          # - "development"
          # - "runtime"
          kind: "all"
          # Supported updates to automerge:
          # - "all"
          # - "security:patch"
          # - "semver:patch"
          # - "semver:minor"
          # - "semver:in_range"
      - match:
          dependency_group: "runtime"
          kind: "semver:patch"
      # Only top level dependencies can be automerged
      - match:
          dependency_name: "rspec"
          kind: "all"

    # Specify what updates are allowed
    #
    # Example: only allow security updates
    allowed_updates:
      - match:
          kind: "security"

    # Specify if you want indirect dependency updates
    # Note: Dependabot will always update insecure indirect dependencies
    #
    # Example: update all indirect/sub-dependencies
    indirect_dependency_updates: "all"
    # Available options:
    # - "all"
    #   Only supported by the following package managers
    #   - "ruby:bundler"
    #   - "go:modules"
    #   - "php:composer"
    #   - "rust:cargo"
    #   - "python"

    # Specify how Dependabot should update your package manifest (e.g.
    # package.json, Gemfile etc) (as opposed to your lockfile)
    #
    # Example: respect the version requirement range defined in your package
    # manfest (e.g. package.json, Gemfile etc) and don't create any updates that
    # are out of range
    version_requirement_updates: "off"
    # Available update strategies:
    # - "off"
    # - "auto": Default (bump versions if an app, widen ranges if a library)
    #    Only supported by the follwing package managers:
    #    - "javascript"
    #    - "ruby:bundler"
    #    - "go:dep"
    #    - "python"
    #    - "php:composer"
    #    - "rust:cargo"
    #    - "elixir:hex"
    #
    # - "widen_ranges": Relax the version requirement when possible
    #    Only supported by the follwing package managers:
    #    - "javascript"
    #    - "go:dep"
    #
    # - "increase_versions": Always increase the version requirement
    #                        to match the new version
    #    Only supported by the follwing package managers:
    #    - "javascript"
    #    - "ruby:bundler"
    #    - "go:dep"
    #
    # - "increase_versions_if_necessary": Increase the version requirement only
    #                                     when required by the new version
    #    Only supported by the follwing package managers:
    #    - "javascript"
    #    - "ruby:bundler"
```

**Comment by RohanNagar** [comment]
@feelepxyz - a quick suggestion I had after reading about the config files. Would it be possible to also look for a Dependabot config file in the `.github/` directory instead of only in the root? Something like `.github/.dependabot/config.yaml`? I only ask because I know a lot of Github apps allow for this already, it would be nice to be able to keep more in the `.github/` folder.

**Comment by greysteil** [comment]
I"m 👍 on that I think. Any reason to use `.github/.dependabot/config.yml` rather than just `.github/dependabot.yml`? (We nest in a directory to allow you to use submodules, but that doesn't seem necessary if already in a `.github` directory.

Also, look like we should support `.yaml` as well as `.yml`...

**Comment by RohanNagar** [comment]
Good point, `.github/dependabot.yml` would be better since it is already nested.

And yes, I didn't even catch that I used `.yaml` instead of `.yml`, would be nice if both were supported!

**Comment by bsideup** [comment]
Hi @greysteil! Any plans to support wildcards? Would be super useful for the multi-module projects like this one:
https://github.com/testcontainers/testcontainers-java/blob/7740a4635df2de978bf9560d153d4a39648004a8/.dependabot/config.yml#L8

**Comment by feelepxyz** [comment]
@bsideup oh nice one! Yeah we’ve done a bunch of thinking on your use case when designing the config file and wildcards is definitely one of the options but haven’t decided approach yet. We’ve also been investigating jsonnet as a way to template the config.

Definitely something I want to get back to once we finalise the current config format!

**Comment by feelepxyz** [comment]
@RohanNagar didn’t know apps supported config in .github but makes sense! Also keen to finalise the current format before supporting more load paths, would also require persisting the file location for linking back to it from the dashboard, which we probably should do anyway, but adds some complexity.

**Comment by connorshea** [comment]
This name took me a bit of time to understand, and I'd say I understand how dependabot works better than most users. FWIW I think you should change this (I think `subdependency_updates` would be a better name).

```yml
# Specify if you want indirect dependency updates
# Note: Dependabot will always update insecure indirect dependencies
#
# Example: update all indirect/sub-dependencies
indirect_dependency_updates: "all"
```

Also, I'm not sure I understand why the option exists in the config if `"all"` is the only available choice right now?

Unrelated, and I know it's still in beta, but for future reference when you need to put together full documentation for this, [the `.gitlab-ci.yml` documentation](https://docs.gitlab.com/ee/ci/yaml/) is the best I've seen for any config file of this sort.

**Comment by connorshea** [comment]
My other piece of feedback is pretty subjective, but it's been bugging me since I first saw the `config.yaml` in the core repo a few days ago, so I figured I'd share it.

The current format uses hyphens to list each package manager type:

```yml
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"

  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "live"
```

This is fine, but personally I think it'd be much easier to follow - especially for big configs - if it was formatted like this:
```yml
version: 1
update_configs:
  javascript:
    directory: "/"
    update_schedule: "daily"

  # I _think_ this is valid YML syntax but I'm not entirely sure? It does look a bit weird but both GitHub and VSCode syntax highlight it properly.
  ruby:bundler:
    directory: "/"
    update_schedule: "live"
```

My reasoning is mostly that it's easier to tell from the indentation when a new package manager section starts, and I also just personal preference for `ruby:bundler:` over `- package_manager: "ruby:bundler"`

**Comment by connorshea** [comment]
FWIW it'd be nice to have some way to see the errors _before_ merging the config into master ;)

https://github.com/connorshea/mdn-compat-data-explorer/issues/226

**Comment by bsideup** [comment]
Hi @feelepxyz! So far so good! I just have a couple of questions:

1) do you think it's possible to also document default values? e.g. `update_schedule`, or `automerged_updates->match->kind`.
2) Is it possible to specify `automerged_updates: true` to auto-merge everything?

**Comment by feelepxyz** [comment]
@connorshea thank you for your detailed and thoughtful feedback!

> This name took me a bit of time to understand, and I'd say I understand how dependabot works better than most users. FWIW I think you should consider changing this (I think `subdependency_updates` would be a better name).
> 
> ```yaml
> # Specify if you want indirect dependency updates
> # Note: Dependabot will always update insecure indirect dependencies
> #
> # Example: update all indirect/sub-dependencies
> indirect_dependency_updates: "all"
> ```
> 
> Also, I'm not sure I understand why the option exists in the config if `"all"` is the only available choice right now?

We struggled quite a bit with the naming of this one! 🤠
Annoyingly every package manager has a different naming convention for indirect/transitive/sub-dependency/package updates, so I think any one we pick we'll have this problem 😞 

For the value we opted for the enum (`all`, `security`) over a boolean as the default boolean case was confusing. For example `indirect_dependency_updates: false` actually means update indirect/sub-dependency with security vulnerabilities.

Currently the default setting is `indirect_dependency_updates: security` - and there's currently no way to turn these off.

> Unrelated, and I know it's still in beta, but for future reference when you need to put together full documentation for this, [the `.gitlab-ci.yml` documentation](https://docs.gitlab.com/ee/ci/yaml/) is the best I've seen for any config file of this sort.

Thanks for the link to the GitLab documentation! Will definitely use that as a reference!

> EDIT: This does have the potential downside of not allowing Dependabot to update multiple e.g. Gemfiles in separate directories (I don't think you can have the same key twice?), I'm not sure if that's something you're interested in supporting here but I thought it was worth mentioning.

You're right, this is the main reason for the current format - we currently support multiple package managers in different directories so need to support this use case.

> To allow for that use case, maybe something like this?
> 
> ```yaml
> version: 1
> update_configs:
>   whatever_name_i_want_here:
>     package_manager: "ruby:bundler"
>     directory: "/"
>     update_schedule: "live"
> ```

I'm with on the benefit of separating configs by a key, would definitely improve legibility. The problem I see with this is that it would make it much harder for us generate a config file from an existing dashboard setup, something we're planning on supporting soon. When generating the config, what should we call each key? We currently don't have any name/description to go on so would have to generate using some combination of directory, package manager and target branch.

Similarly, I want to try and keep things like package manager (e.g. `ruby:bundler`) as a value rather than a key as it makes tooling, validation and errors a bit easier to work with.

> EDIT 2: Why do you need the double-quotes at all? `update_schedule: live` is valid YAML. I can understand it for some things, like the directory, but for a lot of these configuration options quotation marks shouldn't be necessary.

Double-quotes are not required! We've just used them as a convention when documenting but you can write your config file in any valid yaml syntax.

> FWIW it'd be nice to have some way to see the errors _before_ merging the config into master ;)
> 
> [connorshea/mdn-compat-data-explorer#226](https://github.com/connorshea/mdn-compat-data-explorer/issues/226)
> 
> I also noticed that the Dependabot dashboard didn't seem to have any notice about the `config.yml` file being invalid, from the dashboard it looked like everything worked fine.

We should definitely be showing you the validation errors in the dashboard, will add this!
I also like your idea of validating the config file if it's sitting in a PR! Will have a think about how best to do this.

**Comment by feelepxyz** [comment]
@bsideup thanks!

> 1. do you think it's possible to also document default values? e.g. `update_schedule`, or `automerged_updates->match->kind`

Yes we're working on better documentation for all options. Currently `update_schedule` is required so doesn't have a default setting, same goes for `automerged_updates` - where no updates are automerged if you don't specify this.

> 2\. Is it possible to specify `automerged_updates: true` to auto-merge everything?

You can automerge all updates with the following config:

```yaml
automerged_updates:
  - match:
    dependency_group: "development"
    kind: "all"
  - match:
    dependency_group: "runtime"
    kind: "all"
```

**Comment by bsideup** [comment]
@feelepxyz thanks :) What's the config [we ended up with](https://github.com/testcontainers/testcontainers-java/blob/c8a6050841788c79b587e1eadeeb1681c5229d7a/.dependabot/config.yml#L86) but I was hoping that there is an "alias" for it. So, here comes a suggestion: `automerged_updates: true` which is essentially the same as the lines you mentioned but much shorter

**Comment by feelepxyz** [comment]
@bsideup nice! Keen to stabilise the current format first but I'm up for something like your suggestion to automerge all updates. I'm thinking something like `automerged_updates: "all"` might be a bit clearer.

**Comment by greysteil** [comment]
Very minor update: we've just renamed the `semver:in_range` automerge rule to just `in_range`.

**Comment by connorshea** [comment]
@feelepxyz I'm not super familiar with YAML validation so I don't know what's easy/hard to do, but as long as there's a `package_manager` key/value pair for an object I'd think it would still be relatively easy to validate?

Like so:

```yaml
version: 1
update_configs:
  whatever_name_i_want_here:
    package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "live"
```

**Comment by feelepxyz** [comment]
@connorshea yes validation isn't to bad, we're currently validating against a JSON schema and match the specific schema based on the package_manager.

Been thinking this through and pretty sure I want to keep the current format to make it easy to convert existing dashboards configs to a config file, which don't have a good value to use for the key. Once we've implemented this I'm up for revisiting this and possibly supporting different schemas.

The GitLab linter looks nice! Could be a nice addition to the dashboard. Wondering if we should start by validating the config file if it's modified in a PR. What do you think of adding a status check to the PR if you are using a config file?

**Comment by connorshea** [comment]
A status check sounds good to me!

**Comment by greysteil** [comment]
Another update: you can now specify `ignored_updates` in your config file. Doing so will override any ignores that you've specified by commenting `@dependabot ignore this dependency` (or similar) in the past, and disable those commands.

**Comment by greysteil** [comment]
Another update: you can now specify a whitelist of dependencies in your config file using the `allowed_updates` attribute:

```
    allowed_updates:
      - match:
          kind: "security"
      - match:
          dependency_name: "dependabot-core"
      - match:
          dependency_name: "sinatra"
```

The above config would create PRs for security updates to any dependencies, and non-security updates for the `dependabot-core` and `sinatra` dependencies.

**Comment by feelepxyz** [comment]
Few more breaking changes before finalising the current version:

- Rename: `kind` to `update_type`
- Rename: `dependency_group` to `dependency_type`
  - Change value: `runtime` to `production`

Example using the new keys and values:

```yaml
automerged_updates:
  - match:
      dependency_type: "development"
      update_kind: "all"
  - match:
      dependency_type: "production"
      update_kind: "security:patch"
allowed_updates:
  - match:
      update_kind: "security"
```
