### ISSUE TITLE
Different update frequency for a set of dependencies

### ISSUE THREAD

**Issue by louim** [dependabot/feedback#730]
Hey team!

Our `.dependabot/config.yml` looks like this:
```yml
version: 1
update_configs:
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "daily"
    allowed_updates:
      - match:
          update_type: "all"
    ignored_updates:
      - match:
          dependency_name: "rails"
  # Since we are using a rails branch instead of a specific release,
  # we only want a weekly update to prevent update PR spam.
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "weekly"
    allowed_updates:
      - match:
          dependency_name: "rails"
```
Maybe our problem can already be solved, but I was not able to find a working solution. Dependabot seems to only match one `package_manager` (the last one in the config file).

We hoped that using this config, Dependabot would update Rails weekly only, and the other dependencies on a daily basis. Is this possible currently?
