### ISSUE TITLE
Update dependencies on different schedules

### ISSUE THREAD

**Issue by nizhu** [dependabot/feedback#733]
For context, this is for a bog-standard isomorphic React application. I generally liked to update our dependencies as soon as possible, however we found that updating client side dependencies meant our vendor-script bundle is replaced way too often. This is the config file that I came up with, but Dependabot reads only the very last one (maybe I've missed in the docs?)

```
version: 1
update_configs:
  # Development/Building/CI dependencies
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    allowed_updates:
      - match:
          dependency_type: "development"
    ignored_updates:
      - match:
          dependency_name: "@types/react-dom"
    ignored_updates:
      - match:
          dependency_name: "@hot-loader/react-dom"
    ignored_updates:
      - match:
          dependency_name: "react-test-renderer"

  # Client Javascript
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    allowed_updates:
      - match:
          dependency_type: "production"
    ignored_updates:
      - match:
          dependency_name: "react"
    ignored_updates:
      - match:
          dependency_name: "react-dom"

  # Client Javascript - security updates
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "security"
```

The idea is that I'd abuse the definition of `dependency` as scripts that will get sent to browsers and `devDependency` everything else (server/ci/dev/build), so the scheduling becomes:

* Never update react
* Client deps update once a week
* Client deps security update live
* Everything else update daily
