### ISSUE TITLE
Java dependency not ignored

### ISSUE THREAD

**Issue by beatngu13** [dependabot/feedback#759]
We use Dependabot for quite some time now and we are super happy with it. However, today we created a `config.yml` for one of our repos (see [here](https://github.com/retest/recheck-web/blob/master/.dependabot/config.yml)):

```yml
version: 1
update_configs:
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "daily"
    default_reviewers:
      - "beatngu13"
      - "martin-v"
      - "modulo11"
      - "diba1013"
    ignored_updates:
      - match:
          # As long as the issue is not fixed, we need to use version 0.9
          # see https://github.com/assertthat/selenium-shutterbug/issues/64
          dependency_name: "selenium-shutterbug"
```

As can be seen, we want to ignore the selenium-shutterbug dependency, but we immediately received the following PR after downgrading it:

https://github.com/retest/recheck-web/pull/412

Is this due to a bug or are we specifying the dependency not correctly? Does it also expect the group ID or anything else?
