### ISSUE TITLE
Dependabot unassigned required reviewers

### ISSUE THREAD

**Issue by davidsbond** [dependabot/feedback#764]
Hello, my team are using dependabot on a monorepo we have set up. So far it has been working great! 

We've set up a `CODEOWNERS` file which covers all files/directories for a certain team, like so:

```
* @utilitywarehouse/org-partner-platform
```

When anybody opens a PR, I can see the team gets assigned as the reviewer as expected. We've also got dependabot's configuration set up like so:

```yaml

version: 1
update_configs:
  # Go
  - package_manager: "go:modules"
    directory: "/"
    update_schedule: "daily"
    default_reviewers:
      - "org-partner-platform"
```

So whenever it opens a PR, I'd expect it to assign the team as a reviewer. However, what we actually see is that the team gets assigned then removed from the PR, like so:

![image](https://user-images.githubusercontent.com/6227720/68693397-22b4bb80-056f-11ea-9fda-16b9ebdb5d3e.png)

For some reason it assigns then removes the reviewers. Is there an issue in our configuration?
