### ISSUE TITLE
Dependabot config does not understand version suffixes

### ISSUE THREAD

**Issue by gastaldi** [dependabot/feedback#780]
I have a `.dependabot/config.yml` file with the following content: 

```
version: 1
update_configs:
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "daily"
    allowed_updates:
      - match:
          update_type: "security"
      - match:
          dependency_name: "com.microsoft.sqlserver:mssql-jdbc:*.jre8"
```

I want Dependabot to grab the latest version with the `.jre8` suffix. By looking at https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc, Dependabot should have created a PR for the `7.4.1.jre8` version, but nothing happens.
 
Public repository: https://github.com/gastaldi/quarkus
