### ISSUE TITLE
Docker updates for wordpress image

### ISSUE THREAD

**Issue by minac** [dependabot/feedback#816]
Hi!

I have a repository (private) with a `Dockerfile` that currently only has one instruction:
`FROM wordpress:5.3.1-php7.1-fpm-alpine`

The `.dependabot/config.yml` is the following:
```
version: 1
update_configs:
  - package_manager: "docker"
    directory: "/"
    update_schedule: "daily"
    allowed_updates:
      - match:
          update_type: "all"
```

I bumped dependabot using the interface, but no PR came in, even though there are [multiple newer versions in docker hub](https://hub.docker.com/_/wordpress/?tab=description).

I waited for 15 minutes and checked that the bump message was no longer `hold on tight`.

Is this because of the naming structure for the `wordpress` docker image?

Thanks!
