### ISSUE TITLE
docker-compose support

### ISSUE THREAD

**Issue by jvdlaar** [dependabot/feedback#82]
Are there any plans to support docker-compose and version numbers inside the docker-compose.yml file?

Up till now we created a Dockerfile for each image we used, just for dependabot.

This is the format:
```
version: '3.5'

services:
  php-cli:
    build:
      context: '../../docker/php'
      dockerfile: './cli/Dockerfile'
    volumes:
      - ./:/app:cached

  deptrac:
    image: jakzal/phpqa:alpine
    volumes:
      - ./:/app:cached
    working_dir: /app
    command: ["deptrac", "analyze", "--formatter-graphviz=0"]
```
So for cli how we currently do it with Dockerfiles and deptrac with the version direct in the docker-compose.yml
