### ISSUE TITLE
Does dependabot poll private repositories in live mode?

### ISSUE THREAD

**Issue by dominguezcelada** [dependabot/feedback#853]
### Description
We have 4 repositories under the same organization with dependabot configured to get auto-updates of dependencies on `package.json`. We are publishing new versions of packages being used on those `package.json` every day.

Seems dependabot is running a daily (around 6AM) update even though the configuration we are using for update_schedule is `live`.

### Questions
* Does `dependabot` polls private repositories?
   * If so, how often when using `live` _update_schedule_?
* Is there something else missing to make it work as expected?

#### Dependabot's configuration:
```
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "all"
          dependency_type: "direct"
    automerged_updates:
      - match:
          update_type: "in_range"
    version_requirement_updates: "off"
    commit_message:
      prefix: "chore"
```

#### Dependabot's settings:
![image](https://user-images.githubusercontent.com/2574275/74154742-818fdc80-4c13-11ea-9966-a348cce23b3b.png)

Thanks
