### ISSUE TITLE
Provide a way to opt out of major version updates

### ISSUE THREAD

**Issue by sketchbuch** [dependabot/feedback#880]
It would be good if you could specify in the config.yml that you want minor, patch and security updates but not major version change updates. Is this possible now or going to be possible?

**Comment by JustFly1984** [comment]
+1, but I would like to see both PR - major and minor updates, for example @types/node package. In some repositories we are still using node 12, and there is still @types/node@12 updates, but I see only PR for @types/node@13

**Comment by hendrikhalkow** [comment]
Assuming that you have a high test coverage, you can use auto-merging and opt out for major version upgrades:

```
  automerged_updates:
  - match:
      dependency_type: all
      update_type: semver:minor
```

Thus, you will still get the major upgrade PRs, but only minors and patches are auto-merged.
