### ISSUE TITLE
ignored_updates with Go modules either not ignoring or needs more documentation

### ISSUE THREAD

**Issue by stone-z** [dependabot/feedback#913]
This could either be a bug report or just a request for more docs depending on the outcome.

In [this repo](https://github.com/giantswarm/kvm-operator) I am trying to ignore all dependencies from `k8s.io/` which are above a certain version `>= 0.17.0` as I only want patch updates within the 0.16 minor version.

I think it isn't properly matching due to the special characters in the name. I'm not sure what exactly to expect from the `dependency_name` and `version_requirement` fields -- are these proper regular expressions, or is there some limited syntax which dependabot supports?

I've tried this two ways with no success:
```
version: 1
update_configs:
  - package_manager: "go:modules"
    directory: "/"
    target_branch: "master"
    update_schedule: "daily"
    ignored_updates:
      - match:
          # Ignore k8s.io dependencies which aren't 0.16.x
          dependency_name: "k8s.io/*"
          version_requirement: ">=0.17.0"
```

and 

```
version: 1
update_configs:
  - package_manager: "go:modules"
    directory: "/"
    target_branch: "master"
    update_schedule: "daily"
    ignored_updates:
      - match:
          # Ignore k8s.io dependencies which aren't 0.16.x
          dependency_name: |
            k8s\.io\/*
          version_requirement: ">=0.17.0"
```

Can you shed some light here?

**Comment by stone-z** [comment]
Tried it a third way, still no luck:
```
version: 1
update_configs:
  - package_manager: "go:modules"
    directory: "/"
    target_branch: "master"
    update_schedule: "daily"
    ignored_updates:
      - match:
          # Ignore k8s.io dependencies which aren't 0.16.x
          dependency_name: >
            k8s\.io\/.*
          version_requirement: ">=0.17.0"
```

**Comment by stone-z** [comment]
I've done some more experimenting with this over at https://github.com/stone-z/dependabot-sandbox

I _think_ I've narrowed the rule down to one, but the dependabot behavior is still very inconsistent when trying to apply it. For example, applying this rule on my repository seems to exclude the dependencies, but applying the rule on a different repository does not exclude them.

Additionally, branches which previously had open PRs for matching dependencies do not remove those PRs when the rule is added.

So I'm still puzzled.

This is the rule which might maybe work:
```
      - match:
          # Ignore k8s.io dependencies which aren't 0.16.x
          dependency_name: "k8s.io/**"
          version_requirement: ">=0.17.0"
```
