### ISSUE TITLE
Default configuration does not pass Depandabot validation

### ISSUE THREAD

**Issue by merlinnot** [dependabot/feedback#929]
**Package manage/ecosystem**

All.

**Manifest contents prior to update**

```yaml
update_configs:
  - allowed_updates:
      - match:
          dependency_type: all
          update_type: security
      - match:
          dependency_type: direct
          update_type: all
    automerged_updates: []
    commit_message:
      include_scope: true
      prefix: chore
    default_assignees: []
    default_labels: []
    default_reviewers: []
    directory: /
    ignored_updates: []
    package_manager: javascript
    target_branch: master
    update_schedule: live
    version_requirement_updates: increase_versions
version: 1
```

**Updated dependency**

Not relevant.

**What you expected to see, versus what you actually saw**

In the configuration specified above, a few options fail validation:

```yaml
automerged_updates: []
default_assignees: []
default_labels: []
default_reviewers: []
ignored_updates: []
```

For many of these an empty array is a default value.

When these options are specified explicitly, configuration does not pass validation, resulting in the following errors:

```
The property '#/update_configs/0/default_reviewers' did not contain a minimum number of items 1
The property '#/update_configs/0/default_assignees' did not contain a minimum number of items 1
The property '#/update_configs/0/default_labels' did not contain a minimum number of items 1
The property '#/update_configs/0/automerged_updates' did not contain a minimum number of items 1
The property '#/update_configs/0/ignored_updates' did not contain a minimum number of items 1
```

An expectation would be that default values (empty arrays) pass validation, since they are correct configuration options.

**Images of the diff or a link to the PR, issue or logs**

Not relevant.
