### ISSUE TITLE
dependabot automatically merged even when it shouldn't do so

### ISSUE THREAD

**Issue by warden** [dependabot/feedback#952]
dependabot is configured to *not* auto-merge anything (the [default](https://dependabot.com/docs/config-file/#automerged_updates)), however when a dependabot-PR was recreated and the build was fixed, dependabot decided to auto-merge it, regardless of the config settings.

PR: https://github.com/jenkinsci/jira-plugin/pull/245
config - https://app.dependabot.com/accounts/jenkinsci/projects/172233

```
---
update_configs:
- default_reviewers:
  - warden
  - olamy
  directory: "/"
  ignored_updates:
  - match:
      dependency_name: jcl-over-slf4j
      version_requirement: ">= 0"
  - match:
      dependency_name: log4j-over-slf4j
      version_requirement: ">= 0"
  - match:
      dependency_name: org.jenkins-ci.main:jenkins-bom
      version_requirement: ">= 0"
  - match:
      dependency_name: org.jenkins-ci.main:jenkins-core
      version_requirement: ">= 0"
  - match:
      dependency_name: org.jenkins-ci.main:jenkins-war
      version_requirement: ">= 0"
  - match:
      dependency_name: slf4j-api
      version_requirement: ">= 0"
  - match:
      dependency_name: slf4j-jdk14
      version_requirement: ">= 0"
  package_manager: java:maven
  update_schedule: monthly
In addition, the following defaults have been applied:

---
allowed_updates:
- match:
    update_type: all
    dependency_type: direct
- match:
    update_type: security
    dependency_type: indirect
automerged_updates: []
default_assignees: []
default_labels:
- dependencies
target_branch: master
```
