### ISSUE TITLE
Auto-merge in GitHub's native Dependabot

### ISSUE THREAD

**Issue by projectssome** [dependabot/feedback#954]
After I migrated to the GitHub's native Dependabot, the PR's stopped auto merging. How do I enable it? I couldn't find anything about it in the [new documentation](https://help.github.com/en/github/administering-a-repository/keeping-your-dependencies-updated-automatically).

I've also followed the [old documentation](https://dependabot.com/docs/config-file/#automerged_updates) by enabling every option needed, in the account settings, as you can see below.

![Screen Shot 2020-06-06 at 12 08 02 AM](https://user-images.githubusercontent.com/44626533/83934824-e0acca80-a789-11ea-9b40-8d90096303be.png)

Below is my new dependabot.yml file

```
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    open-pull-requests-limit: 100
```
