### ISSUE TITLE
Support wildcard/glob patterns in directory config

### ISSUE THREAD

**Issue by clxmstaab** [dependabot/feedback#970]
when working with the very popular [Composer bin plugin](https://github.com/bamarni/composer-bin-plugin) to isolate your dependencies in a php and composer depenency manager context, the resulting file structure in your repo looks like

```
tree vendor-bin/ -L 2
vendor-bin/
├── churn-php
│   ├── composer.json
│   ├── composer.lock
│   └── vendor
├── clx-active-record-fixer
│   ├── composer.json
│   ├── composer.lock
│   └── vendor
├── php-cs-fixer
│   ├── composer.json
│   ├── composer.lock
│   └── vendor
└── phpstan
    ├── composer.json
    ├── composer.lock
    └── vendor
```

this means for every dependency/tool I managed via the "Composer bin plugin" I need to configure a separate pattern in my `dependabot.conf`.

in our usual projects this looks like

```
version: 2
updates:
  -   package-ecosystem: composer
      directory: /
      schedule:
        interval: daily

  -   package-ecosystem: npm
      directory: /
      schedule:
        interval: daily

  -   package-ecosystem: composer
      directory: /vendor-bin/churn-php/
      versioning-strategy: increase
      schedule:
        interval: daily

  -   package-ecosystem: composer
      directory: /vendor-bin/clx-active-record-fixer/
      versioning-strategy: increase
      schedule:
        interval: daily

  -   package-ecosystem: composer
      directory: /vendor-bin/php-cs-fixer/
      versioning-strategy: increase
      schedule:
        interval: daily

  -   package-ecosystem: composer
      directory: /vendor-bin/phpstan/
      versioning-strategy: increase
      schedule:
        interval: daily
```

the number of entries grows with the number of dependencies managed via "Composer bin plugin".

things would get a lot easier if we could glob/wildcard patterns in the `directory` config. when glob/wildcard patterns would be supported our `dependabot.conf` could get simplified to 

```
version: 2
updates:
  -   package-ecosystem: composer
      directory: /
      schedule:
        interval: daily

  -   package-ecosystem: npm
      directory: /
      schedule:
        interval: daily

  -   package-ecosystem: composer
      directory: /vendor-bin/*/
      versioning-strategy: increase
      schedule:
        interval: daily
```

see the `directory: /vendor-bin/*/` line which would contain "all the magic".
